"""add_bia_impact_criteria_and_levels_tables

Revision ID: c51c477965a4
Revises: 65e32ec2bf46
Create Date: 2025-06-17 19:43:53.512973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c51c477965a4'
down_revision: Union[str, None] = '65e32ec2bf46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bia_impact_criteria',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('organization_id', sa.CHAR(36), nullable=False),
    sa.Column('bia_category_id', sa.CHAR(36), nullable=False),
    sa.Column('parameter_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rating_type', sa.Enum('QUALITATIVE', 'QUANTITATIVE', name='ratingtypeenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.CHAR(36), nullable=True),
    sa.Column('updated_by_id', sa.CHAR(36), nullable=True),
    sa.ForeignKeyConstraint(['bia_category_id'], ['bia_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bia_impact_criteria_bia_category_id'), 'bia_impact_criteria', ['bia_category_id'], unique=False)
    op.create_index(op.f('ix_bia_impact_criteria_organization_id'), 'bia_impact_criteria', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bia_impact_criteria_parameter_name'), 'bia_impact_criteria', ['parameter_name'], unique=False)
    op.create_table('bia_impact_criterion_levels',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('bia_impact_criterion_id', sa.CHAR(36), nullable=False),
    sa.Column('organization_id', sa.CHAR(36), nullable=False),
    sa.Column('level_name', sa.String(length=255), nullable=True),
    sa.Column('level_value_min', sa.Float(), nullable=True),
    sa.Column('level_value_max', sa.Float(), nullable=True),
    sa.Column('quantitative_level_descriptor', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.CHAR(36), nullable=True),
    sa.Column('updated_by_id', sa.CHAR(36), nullable=True),
    sa.ForeignKeyConstraint(['bia_impact_criterion_id'], ['bia_impact_criteria.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bia_impact_criterion_levels_bia_impact_criterion_id'), 'bia_impact_criterion_levels', ['bia_impact_criterion_id'], unique=False)
    op.create_index(op.f('ix_bia_impact_criterion_levels_organization_id'), 'bia_impact_criterion_levels', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bia_impact_criterion_levels_organization_id'), table_name='bia_impact_criterion_levels')
    op.drop_index(op.f('ix_bia_impact_criterion_levels_bia_impact_criterion_id'), table_name='bia_impact_criterion_levels')
    op.drop_table('bia_impact_criterion_levels')
    op.drop_index(op.f('ix_bia_impact_criteria_parameter_name'), table_name='bia_impact_criteria')
    op.drop_index(op.f('ix_bia_impact_criteria_organization_id'), table_name='bia_impact_criteria')
    op.drop_index(op.f('ix_bia_impact_criteria_bia_category_id'), table_name='bia_impact_criteria')
    op.drop_table('bia_impact_criteria')
    # ### end Alembic commands ###
